sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t sivakumargollu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sivakumargollu/docker-react  npm run test

